blank_issues_enabled: false
contact_links:
  - name:  Documentaci贸n
    url: https://github.com/javiprieto89/Llevar/tree/master/Docs
    about: Consulta la documentaci贸n completa del proyecto
  - name:  Gu铆a de Contribuci贸n
    url: https://github.com/javiprieto89/Llevar/blob/master/CONTRIBUTING.md
    about: Aprende c贸mo contribuir al proyecto
  - name:  Reporte de Seguridad
    url: https://github.com/javiprieto89/Llevar/security/advisories/new
    about: Reporta vulnerabilidades de seguridad de forma privada
